name: Docker Repository CI

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Node.js Test']
    types: [completed]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      id: login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}:webapp
    - name: Push the Docker image
      id: push
      run: docker push ${{ secrets.DOCKER_USER }}:webapp
